name: build MernAppWorkflow
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Node.js and react 18.3.1
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: install mongo
              run: npm install mongoose
            - name: change to backend
              run: ./simple-mern-app/backend
            - name: run backend
              run: node server.js

              




